# Site settings
title: Optical Nano-Technology Laboratory
email: gistontl@gist.ac.kr
description: ""
baseurl: ""
url: "http://ontl.gist.ac.kr"
laboratory_name: Optical Nano-Technology Laboratory
affiliation_name: School of Infomation and Communications, Gwangju Institute of Science and Technology
affiliation_city: Gwangju
affiliation_country: Republic of Korea

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
